### ISSUE TITLE
LDAP group members are not synced correctly

### ISSUE THREAD

**Issue by EinhornSylar** [bitwarden/directory-connector#103]
We are syncing users and groups from our OpenLDAP to bitwarden. But some groups are missing users. The users themselves are synced correctly they are just missing in the group in bitwarden. After removing the user from the group and adding them again they correctly appear in the group.

For Example user 'A' and user 'B' are members of the group 'team-x' in LDAP. When we sync this to bitwarden only 'B' is shown to be a member of 'team-x'. Only after removing 'A' from the group in LDAP and adding him again the sync adds 'A' to 'team-x' in bitwarden.

We couldn't find a connection between the affected users or groups. We are using version 2.9.1 of the connector.

**Comment by martbhell** [comment]
@EinhornSylar hey sorry to hijack this post, I haven't been able to get OlenLDAP and group memberships to work at all. How does an ldap group look like in your setup? Are the members in memberAttribute the DN of the member? 

(We've been using the short uid of each member for all other services)

**Comment by martbhell** [comment]
Replying to myself: it has to be with DNs. GroupOfNames work, posixGroups does not.
