### ISSUE TITLE
Cannot Sync AD user BWDC CLI. Deleted users  

### ISSUE THREAD

**Issue by amc950** [bitwarden/directory-connector#105]
The email attribute (displayName in DC) for the deleted users returned from active directory are duplicates and preventing a sync. It would be best to create an error message that indicates there is a "Duplicate email address in the Deleted Users", then the user can know that they need to change or hard delete one of the deleted users to prevent the conflict. We may see the use case where an admin is unable to change or delete a deleted user and in this case we may want to enable an optional filter that will allow us to filter out one of the deleted users with the duplicate email address.

**Comment by sethlyons** [comment]
\>>"Duplicate email address in the Deleted Users"
If that could even say which users have the duplicates, it would be awesome!

**Comment by winklevos** [comment]
I am seeing this as well trying to sync with AD with an existing bitwarden org. However the deleted users do not actually duplicate any existing active AD users or existing Bitwarden Users

The error in the Connector UI also disappears and is not retrievable which isn't very helpful
