### ISSUE TITLE
Can't sync my ldap since 2.5

### ISSUE THREAD

**Issue by noldar** [bitwarden/directory-connector#13]
Since directory connector (macos) did an auto-update from 2.4 to 2.5.1, my sync with ldap is broken, I can't even do a "test", no errors, nothing.

I reinstalled 2.5, same issue.

I reinstalled the 2.4 version, everything is OK.

**Comment by kspearrin** [comment]
Can you try going to View > Developer Tools and see if there are any errors in the console?

**Comment by noldar** [comment]
Thanks, there a warning doing a test with sync cache cleared : 

> internal/process/warning.js:18 (node:20085) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> writeOut @ internal/process/warning.js:18
> 

After that it show the user and group search, last message is : 

> [16:33:30.848] Update for version 2.5.1 is not available (latest version: 2.5.1, downgrade is disallowed).

And nothing happens.

**Comment by kspearrin** [comment]
Hm. Is this active directory or some other LDAP?

**Comment by noldar** [comment]
It's openldap

**Comment by noldar** [comment]
<img width="1297" alt="bitwarden" src="https://user-images.githubusercontent.com/6649869/54835069-b0caf180-4cc1-11e9-95ab-027e0af77838.png">

**Comment by kspearrin** [comment]
Looks to be related to https://github.com/joyent/node-ldapjs/issues/483 when we moved to Electron 3. Looking into moving to ldapts to try to resolve the problem.

**Comment by kspearrin** [comment]
Should be fixed in next version.

**Comment by kspearrin** [comment]
@noldar v2.5.2 is now live. Can you give it a try and let me know, please?

**Comment by noldar** [comment]
I'll test monday first hour at work and let you know.

Thank you for your awesome reactivity.

**Comment by noldar** [comment]
Hi @kspearrin 

I confirm all is well working on v2.5.2 👍 

Thank you again for your work and your reactivity!
