### ISSUE TITLE
389ds: missing paged control

### ISSUE THREAD

**Issue by kvaps** [bitwarden/directory-connector#16]
`
Hi I have configured sync with FreeIPA server:
```
{
	"directoryType": 0,
	"directoryConfig_0": {
		"ssl": true,
		"sslAllowUnauthorized": false,
		"port": "636",
		"currentUser": false,
		"ad": false,
		"password": "[STORED SECURELY]",
		"hostname": "freeipa.example.org",
		"rootPath": "cn=accounts,dc=example,dc=org",
		"username": "uid=bitwarden-svc,cn=users,cn=accounts,dc=example,dc=org"
	},
	"syncConfig": {
		"users": true,
		"groups": true,
		"interval": 5,
		"removeDisabled": false,
		"useEmailPrefixSuffix": false,
		"creationDateAttribute": "createTimestamp",
		"revisionDateAttribute": "modifyTimestamp",
		"emailPrefixAttribute": "uid",
		"memberAttribute": "member",
		"userObjectClass": "person",
		"groupObjectClass": "groupOfNames",
		"userEmailAttribute": "mail",
		"groupNameAttribute": "cn",
		"groupPath": "cn=groups,cn=accounts,dc=example,dc=org",
		"userPath": "cn=users,cn=accounts,dc=example,dc=org",
		"userFilter": "(!(uid=*-svc))"
	}
}
```

But when I try to sync, I have an error:

```bash
./bwdc test
missing paged control
```

**Comment by kspearrin** [comment]
What is the size of this result set? it is large?

**Comment by kvaps** [comment]
Yep, should be

**Comment by kspearrin** [comment]
does it work if you limit the result size to a smaller one?

**Comment by kvaps** [comment]
How can I do that? Is there some specific setting for that?

**Comment by kspearrin** [comment]
Try creating a more restrictive filter

**Comment by kvaps** [comment]
I've tried two things:
1) Change search filter to: `(uid=kvaps)`
2) Change search path to single entry, like `uid=kvaps,cn=users,cn=accounts,dc=example,dc=org`

Same problem.

**Comment by kspearrin** [comment]
Maybe it is some issue with ldapjs (the library that we use for LDAP in this application) and FreeIPA. Do you know where there is a FreeIPA test server I could use to try to reproduce this issue?

**Comment by kvaps** [comment]
Hi @kspearrin, I'm not sure, but you can try with freeipa docker image:
https://hub.docker.com/r/freeipa/freeipa-server

**Comment by kspearrin** [comment]
@kvaps I found the following demo server: https://www.freeipa.org/page/Demo

Though I am having a hard time trying to connect to it. Do you know what the settings for this demo server should be exactly?

**Comment by kvaps** [comment]
@kspearrin, try that:

```
	"directoryType": 0,
	"directoryConfig_0": {
		"ssl": true,
		"sslAllowUnauthorized": true,
		"port": "636",
		"currentUser": false,
		"ad": false,
		"password": "Secret123",
		"hostname": "ipa.demo1.freeipa.org",
		"rootPath": "cn=accounts,dc1=demo1,dc=freeipa,dc=org",
		"username": "uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org"
	},
	"syncConfig": {
		"users": true,
		"groups": true,
		"interval": 5,
		"removeDisabled": false,
		"useEmailPrefixSuffix": false,
		"creationDateAttribute": "createTimestamp",
		"revisionDateAttribute": "modifyTimestamp",
		"emailPrefixAttribute": "uid",
		"memberAttribute": "member",
		"userObjectClass": "person",
		"groupObjectClass": "groupOfNames",
		"userEmailAttribute": "mail",
		"groupNameAttribute": "cn",
		"groupPath": "cn=groups,cn=accounts,dc=demo1,dc=freeipa,dc=org",
		"userPath": "cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org",
		"userFilter": ""
	},
```

Agree, I have the same problem with the public demo server

**Comment by kspearrin** [comment]
Works for me with these settings:

	"directoryConfig_0": {
		"ssl": true,
		"port": "636",
		"currentUser": false,
		"ad": false,
		"password": "[STORED SECURELY]",
		"sslAllowUnauthorized": true,
		"sslCertPath": "",
		"hostname": "ipa.demo1.freeipa.org",
		"username": "uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org",
		"sslCaPath": "",
		"rootPath": "dc=demo1,dc=freeipa,dc=org"
	},
	"syncConfig": {
		"users": true,
		"groups": true,
		"interval": 5,
		"removeDisabled": true,
		"useEmailPrefixSuffix": false,
		"creationDateAttribute": "whenCreated",
		"revisionDateAttribute": "whenChanged",
		"emailPrefixAttribute": "sAMAccountName",
		"memberAttribute": "member",
		"userObjectClass": "person",
		"groupObjectClass": "group",
		"userEmailAttribute": "mail",
		"groupNameAttribute": "name",
		"groupPath": "cn=groups,cn=accounts",
		"userPath": "cn=users,cn=accounts",
		"userFilter": "",
		"groupFilter": ""
	},

Looks like your pathing is repeated. user/group paths should not also include the root path. You can debug the LDAP queries from the output in the console under View > Developer Tools.

**Comment by kvaps** [comment]
I'm agree, works for me too. Thanks!
It would be nice for add more informative error.
Close?
