### ISSUE TITLE
data.json not found on portable windows exe

### ISSUE THREAD

**Issue by fgierlinger** [bitwarden/directory-connector#23]
Hello,

After running the portable windows Bitwarden connector, i expected the configuration file (data.json) to be under `%AppData%/Bitwarden Directory Connector/`. The directory contains only one folder `logs` which is also empty.

Can you tell me where the portable windows exe stores the `data.json` file?

Cheers,
Frédéric

**Comment by fgierlinger** [comment]
Ok, so a full disk scan revealed the location. The directory is created in the directory where the portable exe is stored. In my case it was `%HOMEPATH%/Downloads/bitwarden-connector-appdata/`.

It would be great if the documentation would also list the location for the mobile executable. (https://help.bitwarden.com/article/directory-sync/#command-line-interface)

**Comment by kspearrin** [comment]
Yes, the portable app keeps everything locally to the same directory as the exe.

**Comment by fgierlinger** [comment]
I would still recommend to do an update to the documentation (https://help.bitwarden.com/article/directory-sync/#command-line-interface) to reflect the behaviour of the portable exe.
