### ISSUE TITLE
bwdc-linux: Self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by edermi** [bitwarden/directory-connector#25]
Hi,

I'm running latest Bitwarden and I want to migrate from the Desktop Sync application on Windows to the CLI on Linux.

I installed the contents of the zip to `/usr/local/bin` and made sure that all dependencies are met.

System: Debian 9 amd64

Unfortunately, I'm not able to log in:

~~~
root@pwsafe:~# bwdc config server https://pwsafe.mylocal.domain/
Saved setting `server`.
root@pwsafe:~# bwdc login --method 1
? Email address: <account-for-sync>
? Master password: [hidden]
request to https://pwsafe.mylocal.domain/api/accounts/prelogin failed, reason: self signed certificate in certificate chain
~~~

We have a local PKI and this works fine with Bitwarden and the sync client from the Domain-joined Windows system. The CA is also installed on the linux server where the sync client runs:

~~~
root@pwsafe:~# openssl s_client -connect pwsafe.mylocal.domain:443
CONNECTED(00000003)
<SNIP>
verify return:1
---
Certificate chain
<SNIP>
---
Server certificate
-----BEGIN CERTIFICATE-----
<SNIP>
-----END CERTIFICATE-----
<SNIP>
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 9582 bytes and written 269 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: F222F3510AC10B96391785026656DB143E268C67DD522BC64EEEC57CB0AE783A
    Session-ID-ctx:
    Master-Key: 8B204E3ABC1C29E9627B7D8E02D23D34634EFEBC0FDC723D99F44F9D09AD115F63F9D9578CEA1BDD56CDFEB2710FD43B
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1562846182
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
~~~

Is there anything I have to configure beforehand? In my understanding, bwdc should use the system's certificate store.

**Comment by kspearrin** [comment]
I don't think node.js uses the certificate store from the OS. It has it's own list of trusted CAs.

According to the docs, you can extend this with an environment variable to include more CAs. See: https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs

Does that work?

**Comment by edermi** [comment]
Well, interesting behavior... the environment variable seems to work. Nevertheless, I think it's a bit error-prone to keep such settings in an environment variable as I'm a fan of explicit configuration. Same goes by the way for `BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS`. I'm already writing a wrapper around bwdc setting the environment before I managed to successfully log in.

Having the environment stuff as configuration option in bwdc would be nice, at least I think the certificate thing should be documented.
