### ISSUE TITLE
bwdc is not honoring env variable config for BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS

### ISSUE THREAD

**Issue by znaiman** [bitwarden/directory-connector#27]
Following the instructions for running the bwdc cli on headless linux I set the environmental variable BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS to true. However, I still get the error "Cannot autolaunch D-Bus without X11 $DISPLAY" 

```
[root bw]# bwdc --version
2.6.1
[root bw]# echo $BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS
true
[root bw]# bwdc test
Cannot autolaunch D-Bus without X11 $DISPLAY
[root bw]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by kspearrin** [comment]
The instructions in the help center were published a bit early. `BITWARDENCLI_CONNECTOR_PLAINTEXT_SECRETS` will be available in version 2.6.2, which should be released in the coming week or two. You can get the latest dev build from here: https://ci.appveyor.com/project/bitwarden/directory-connector/builds/26246708/job/l6nm6qaehrfxpbl8/artifacts

**Comment by znaiman** [comment]
Thanks!

**Comment by motey** [comment]
still not released?

**Comment by kspearrin** [comment]
2.6.2 is released now.
