### ISSUE TITLE
Local LAN IP as LDAP server host?

### ISSUE THREAD

**Issue by bryanjuho** [bitwarden/directory-connector#274]
Hi, I'm trying to use this in our self-hosted bitwarden + local LDAP (hosted via Synology DSM).
However settings a lan address (ex. 192.168.0.100:389) as the ldap host gives me the error: "invalid DN".
I am pretty sure my DN settings are correctly configured, leaving Local LDAP host the remaining suspect.

Is local LDAP host unsupported? Or are by settings really wrong :( 
Any comments would be appreciated.
Thanks.

**Comment by eliykat** [comment]
Hi @bryanjuho, I've done development and testing work with a local LDAP host at 127.0.0.1. There's nothing I can think of that would prohibit a LAN IP from being used - or that would give you an invalid DN message.

If you've double checked your DN settings, I suggest reaching out to our customer success team for assistance in troubleshooting your configuration.

**Comment by bryanjuho** [comment]
@eliykat 
Thank you for the response. Knowing local LDAPs work well, I will check my settings again.
