### ISSUE TITLE
Documentation lacks information regarding CLI usage

### ISSUE THREAD

**Issue by edermi** [bitwarden/directory-connector#29]
The [documentation](https://help.bitwarden.com/article/directory-sync/#command-line-interface) for setting up bwdc cli doesn't really help. For example, logging in when 2-FA is enabled doesn't work (the tool says the password is wrong). The help says that a special `method` parameter needs to be provided and that those methods are documented, but I didn't find any of them in the documentation.

~~~
bwdc login --help
Usage: login [options] [email] [password]

Log into a user account.

Options:

  --method <method>  Two-step login method.
  --code <code>      Two-step login code.
  -h, --help         output usage information

  Notes:

    See docs for valid `method` enum values.

  Examples:

    bw login
    bw login john@example.com myPassword321
    bw login john@example.com myPassword321 --method 1 --code 249213
~~~

Can you please add instructions how to use the CLI application with 2-FA enabled to the docs?

**Comment by kspearrin** [comment]
Docs have been updated to include 2fa method enum values.

https://help.bitwarden.com/article/directory-sync/#enums
