### ISSUE TITLE
GUI App Updates Fail

### ISSUE THREAD

**Issue by dnuzum** [bitwarden/directory-connector#292]
We currently use the GUI instead of CLI/our cloud instance provider due to some technical limitations at this time. I've experienced this bug for the past year since we launched internally, and no app updates have solved it. 

I previously thought it was my Intel-based MBP, but unfortunately, the `2022.11.0` release ruled that out today. For some time context, why wasn't it caught in `2022.6.0` by myself? That was when I was migrating to an Apple Silicon-based host and downloaded a fresh copy of `2022.6.0`.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/16262553/209990255-fc3a6257-9d07-43f8-9631-b7c435d87541.png">

`Update Error`
```Error: Cannot download "https://github.com/bitwarden/directory-connector/ releases/download/v2022.11.0/Bitwarden-Directory-Connector-2022.11.0-mac.zip", status 404:
at ClientRequest. <anonymous> (/Applications/Bitwarden Directory
Connector.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:229:34)
at ClientRequest.emit (node:events:394:28)
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/ browser_ init:101:6816)
at SimpleURLLoaderWrapper.emit (node:events:394:28)```

**Comment by eliykat** [comment]
Hi @dnuzum, it looks like an issue with our release pipeline having a mismatch in the artifact name. (The correct URL is https://github.com/bitwarden/directory-connector/releases/download/v2022.11.0/Bitwarden-Connector-2022.11.0-mac.zip - without `-Directory` in the filename.) I've asked our devops team to investigate.

**Comment by addisonbeck** [comment]
@dnuzum I'm closing this issue as it was resolved a long time ago, but let me know if you have any concerns.
