### ISSUE TITLE
An unhandled server error has occurred.

### ISSUE THREAD

**Issue by nemchik** [bitwarden/directory-connector#293]
```
api.bitwarden.com/public/organization/import:1 Failed to load resource: the server responded with a status of 500 ()

vendor.js:23388 ERROR Error: Uncaught (in promise): ErrorResponse: {"response":{"object":"error","message":"An unhandled server error has occurred.","errors":null},"message":"An unhandled server error has occurred.","captchaRequired":false,"statusCode":500}
    at resolvePromise (vendor.js:544603)
    at vendor.js:544510
    at rejected (broadcaster.service.ts:5)
    at ZoneDelegate.invoke (vendor.js:543748)
    at Object.onInvoke (vendor.js:45936)
    at ZoneDelegate.invoke (vendor.js:543747)
    at Zone.run (vendor.js:543508)
    at vendor.js:544666
    at ZoneDelegate.invokeTask (vendor.js:543782)
    at Object.onInvokeTask (vendor.js:45923)

vendor.js:546431 09:28:56.715 › Received API exception: [object Object]
```

These 3 errors are showing up in the dev console when trying to sync one of my secondary domains (I have 5 domains, 4 of which sync without issue). On CLI I only get `An unhandled server error has occurred.` (not very helpful). I had to use the GUI to see the issue in the dev tools console. I did notice other similar issues here on GH, but one mentioned duplicate users (I do not believe that is the case for me, but I have had some users change primary email domains?) and the other mentioned self hosting (I am not self hosting).

**Comment by SergeantConfused** [comment]
Hi @nemchik,

Thank you for this report. There are numerous reasons to encounter this error message in the Directory Connector, including subscription related matters; Could you please create a support ticket (https://bitwarden.com/contact/) using the Owner-type email address of that organization, so we'll assist in troubleshooting? Please include a link to this GitHub thread in your message.

We use GitHub issues as a place to track bugs and other development related issues. I will close this GitHub report at this point.


Thank you again.
