### ISSUE TITLE
Support nested groups

### ISSUE THREAD

**Issue by Nothing4You** [bitwarden/directory-connector#3]
Hey there,

imagine I have a security group Foo that contains Bar (group) and Baz (person). Group Bar contains Qux (user). When I sync this setup using this tool it will set up groups Foo and Bar, however, group Foo only contains Baz as member.

**Comment by kspearrin** [comment]
Directories can have nested groups, however, in Bitwarden groups are flat. The connector tool will flatten all groups and user membership.

For example:

- Group A
  - Group B
    - User 2
  - User 1

This will create 2 groups in Bitwarden: Group A and Group B.

Group A will include User 1 and User 2 while Group B will User 2.

Is this not what you are seeing/expecting?

**Comment by kspearrin** [comment]
This is fixed in 2.0. The flattening logic in 1.x was broken.
