### ISSUE TITLE
Unable to Sync with Active Directory

### ISSUE THREAD

**Issue by xardoniak** [bitwarden/directory-connector#31]
Hi!
I'm attempting to set up Directory Connector on my Domain Controller, to link in with my Bitwarden docker installation ( mprasil/bitwarden:latest ), on an Ubuntu VM in the same subnet.
When clicking on Sync, I have shown an error, "An unexpected error has occurred"

Hitting the "Test now" button displays a list of AD accounts with email addresses, as intended.
[See here](https://pasteboard.co/IGoNVMl.png)

Hitting the "Sync" button shows the error, and also an error in the Developer console
[See here](https://pasteboard.co/IGoOfuw.png)

[My Domain settings](https://pasteboard.co/IGoOvCE.png)

I've tried version 2.6.1 and 2.6.2 and I did try one of the earlier version but I cannot remember which one now

Please do keep in mind this is a homelab :)

**Comment by kspearrin** [comment]
> to link in with my Bitwarden docker installation ( mprasil/bitwarden:latest )

You should reach out to @dani-garcia for help with that server instance. I don't know if they support directory connector.

**Comment by sconnery** [comment]
I am having the same issue on Server 2019 / Also tried Azure AD , Same error message.

**Comment by vk4ever** [comment]
> Hi!
> I'm attempting to set up Directory Connector on my Domain Controller, to link in with my Bitwarden docker installation ( mprasil/bitwarden:latest ), on an Ubuntu VM in the same subnet.
> When clicking on Sync, I have shown an error, "An unexpected error has occurred"
> 
> Hitting the "Test now" button displays a list of AD accounts with email addresses, as intended.
> [See here](https://pasteboard.co/IGoNVMl.png)
> 
> Hitting the "Sync" button shows the error, and also an error in the Developer console
> [See here](https://pasteboard.co/IGoOfuw.png)
> 
> [My Domain settings](https://pasteboard.co/IGoOvCE.png)
> 
> I've tried version 2.6.1 and 2.6.2 and I did try one of the earlier version but I cannot remember which one now
> 
> Please do keep in mind this is a homelab :)

Did you get any information regarding this issue from @dani-garcia?
