### ISSUE TITLE
Search Paths are not corretly Built when Root Path does not contain a 'dc=' path

### ISSUE THREAD

**Issue by cirk2** [bitwarden/directory-connector#34]
When the Root Path setting does not contain a `dc=` part the search path is not build correctly.
Test case:
Root Path `o=organisation`
User Path `ou=hr,o=organisation`

Test sync logs to terminal: 
`[16:45:08.440] [info] User search: ou=hr,o=organisation,n => (&(&(objectClass=inetOrgPerson)) (|(employeeType=developer)(employeeType=office)))`
Notice the rouge `,n` at the end of the path, resulting in a wrong DN

When configuring the Root path as `o=organisation,dc=domaincontroller` and User Path as `ou=hr,o=organisation` the console logs `User search: ou=hr,o=organisation,dc=domaincontroller => [...]` as expected.

When I see it correctly this would be caused by :
https://github.com/bitwarden/directory-connector/blob/bf278729737729700a27d596a685fecad1793d4f/src/services/ldap-directory.service.ts#L236
when `indexOf` does not find the search term `dc=` it will return -1, and `substr` therefore will extract the last character from the string. This results in the `,n` suffix in the test case above.

Tested with Linux AppImage version 2.6.2

**Comment by kspearrin** [comment]
I assumed that all paths had a `dc=_______` in them. Is this not the case?

**Comment by cirk2** [comment]
We're just using a plain LDAP (with apache ds as server) and do not use ActiveDirectory. Nothing requires the use of a dc entry in our setup.

**Comment by kspearrin** [comment]
Should be resolved with https://github.com/bitwarden/directory-connector/commit/bc927a65ac14bc492d4f589a2aca1aa3e9a1be02 in the upcoming version.
