### ISSUE TITLE
Users from LDAP does not sync to Bitwarden

### ISSUE THREAD

**Issue by Romich777** [bitwarden/directory-connector#36]
bwdc store wrong data in cache.
`sync` command doesn't make any changes but users in Bitwarden and LDAP out of sync.
`test` command returns correct users list from LDAP.
`last-sync users` - shows that users were synced an hour ago. But in Bitwarden no new users for a week.

Only clear-cache & sync make full sync.
Is it normal behavior? What is bwdc sync TTL? 

bwdc v 2.6.2
Headerless Ubuntu server

**Comment by marcquark** [comment]
+1 had the same problem today.
