### ISSUE TITLE
Release tags do not belong to any branch

### ISSUE THREAD

**Issue by FliegendeWurst** [bitwarden/directory-connector#370]
When visiting a tagged release (e.g. https://github.com/bitwarden/directory-connector/tree/v2023.10.0), there is a scary warning:

    This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Most other GitHub projects point their release tags at some commit on a branch pushed to the repository.

**Comment by eliykat** [comment]
Hi @FliegendeWurst, this is an unfortunate (but expected) side effect of our release strategy.

When preparing for a release, we create an `rc` (release candidate) branch from `master` for regression testing. Any bug fixes during the regression period are merged to `master` but then cherry-picked to `rc` - which means the branches diverge. To cut the release, we tag the head of `rc` with the release number (e.g. v2023.10.0) and then delete the `rc` branch.

This is how we end up with a tag pointing to a commit that does not belong to a branch. It's definitely in the repository though, so while I agree it's a scary message it's not an immediate cause for concern.

git branching strategy has been much discussed internally and definitely something we'd like to improve in the future as our processes improve.

**Comment by FliegendeWurst** [comment]
> It's definitely in the repository though (note the message only says "may belong to a fork")

Yeah, I didn't really expect you to point release tags at anything other than your own repo. It was just suprising to see that warning pop up.

Thanks for the clarification!
