### ISSUE TITLE
Limited to 100 users per group when syncing with Azure AD

### ISSUE THREAD

**Issue by kolja1507** [bitwarden/directory-connector#38]
Although BWDC recognizes all 100+ users in our Azure AD, it only assigns up to (the first) 100 to a single group (sync test & actual sync). If the missing group members (no. 101, 102, ...) are added manually on the browser, BWDC removes (only) them from that group with the next sync.

Tested with BWDC v2.6.2 on macOS, logged in to a self-hosted BW environment running server version 1.33.1 with an Enterprise plan. Might be a coincident: We used to have exactly 100 user seats with our license but increased that limit to 110 recently.

What I've tried so far (mainly because I assumed BWDC would still have our previous 100 user seats in its cache):
- Rebooted machine running BWDC
- Cleared BWDC sync cache
- Logged out of BWDC and in again
- Deleted `~/Library/Application Support/Bitwarden Directory Connector`
- Reinstalled BWDC app (desktop & CLI)
- Ran BWDC in different macOS accounts
- Removed and re-added app registration in AAD
- Re-downloaded `bitwarden_organization_license.json` from our bitwarden.com organization & re-uploaded it to our self-hosted environment
...

I might be wrong but suspect that it might have something to do with the [paging of MS Graph data](https://docs.microsoft.com/en-us/graph/paging) and its [`$top` query parameter](https://docs.microsoft.com/en-us/graph/query-parameters#top-parameter) to specify the page size of the result set when getting the members of an AAD group. [Quote](https://github.com/microsoftgraph/microsoft-graph-docs/issues/4636):

> If the request is paged and you don't added the `$top` query parameter, is there a default or maximal page size on the request? If yes, how big are they?
> 
> Unfortunately (per the referenced page) there's no consistency across APIs on the default or maximum size. For example, **in Azure AD (users, groups, devices etc) the default is 100** and max 999.

Let me know if you need any additional information from me. Thanks!

**Comment by kspearrin** [comment]
Thanks for the report. It looks like we didn't have paging accounted for in the group members API calls. I added that in https://github.com/bitwarden/directory-connector/commit/8b2fa8405b69bb81cf28680bd04016d5db693d70.

Can you try this latest dev build and see if it works as expected? 
https://ci.appveyor.com/project/bitwarden/directory-connector/build/job/vsic9mptaeft2ubf/artifacts

**Comment by kolja1507** [comment]
Thanks for the quick debugging! Unfortunately though, the latest dev build causes this error message when running a test sync with our config:

`Cannot read property 'length' of undefined`

I've already deleted the `data.json` and reconfigured BWDC but that doesn't make a difference. This problem doesn't occur when using v2.6.2

**Comment by kspearrin** [comment]
Can you try the more up-to-date dev build here: https://ci.appveyor.com/project/bitwarden/directory-connector/build/job/0bnbhinwvkvbmsbm/artifacts

**Comment by kolja1507** [comment]
Looks good, thanks! Both the original bug and the recent error message seem to be fixed. Looking forward to the final release of v2.7.0 :)

**Comment by kolja1507** [comment]
As expected, the final release of v2.7.0 doesn't have this bug anymore. Thanks! I'm closing this ticket...
