### ISSUE TITLE
Importing more than 200 groups silently fails

### ISSUE THREAD

**Issue by hajekj** [bitwarden/directory-connector#39]
Larger organizations have hundreds or thousands of security groups which would then get synced into Bitwarden (project groups for example). The API currently limits the import to contain [only 200 groups](https://github.com/bitwarden/server/blob/d6ed8291e644593bc1047ee2175d96f56e61fafe/src/Api/Controllers/OrganizationsController.cs#L377) and eventually 1,000 users.

What I did to avoid this is to split the import task into the user part and group batched part (sending groups by 200). Is this the correct approach? What's the reason for these limits?

The batched split is available in this fork: https://github.com/hajekj/directory-connector/blob/master/src/services/sync.service.ts#L90

**Comment by kspearrin** [comment]
These limits were just put in place as a sanity check. Since we are seeing use cases that challenge these limits, I have increased them both to 2k in the next release.

Splitting the imports into multiple operations should work as long as you don't use the "overwrite" option under settings.

**Comment by hajekj** [comment]
Perfect, thank you!
