### ISSUE TITLE
Renamed user deleted and created as new, instead of renamed, losing data

### ISSUE THREAD

**Issue by BioSehnsucht** [bitwarden/directory-connector#397]
I just had a user being renamed in LDAP (FreeIPA) due to changing last name, and the connector happily updated Bitwarden... but not in an ideal fashion.

Instead of renaming the user in bitwarden (as for example, the Okta connector did for our Atlassian Access integration by leveraging `ipauniqueid` entry to see that it was a rename and not a deletion/creation), it deleted the existing user (and thus any saved credentials and such) and created a new one, sending them a new invite for the new account.

Was there a config entry I missed that would set the unique attribute, so that it would properly rename, or is that not a supported thing?

**Comment by eliykat** [comment]
Hi @BioSehnsucht, I suspect this is intended behaviour based on your configuration. Please contact our Customer Success team who can help you review your configuration and debug the issue: https://bitwarden.com/contact/.

If it does turn out to be a bug, we can re-open this issue. Thanks!
