### ISSUE TITLE
Root path not working with uppercase variables names after 2.7.0 update

### ISSUE THREAD

**Issue by pachulo** [bitwarden/directory-connector#48]
Before the update, this worked OK:

`DC=OurCompany,DC=net`

But after the update to 2.7.0, it didn't.
We needed to change it for:

`dc=OurCompany,dc=net`

The problem is now solved, but do you have any idea why is it so?

**Comment by kspearrin** [comment]
There was this change, but I am not sure how it would have caused your issue:
https://github.com/bitwarden/directory-connector/commit/acfa8632af9ff1c164f84f29be60e105ca7f6b54
