### ISSUE TITLE
Unable to sync when using either directory connector or CLI

### ISSUE THREAD

**Issue by twindarkness321** [bitwarden/directory-connector#481]
Directory Connector version: 2024.3.2
Cli version: 2024.3.2

Hello, This is my first time trying to set up bitwarden directory connector in a self-hosted setup. I am able to log into the directory connector app and after entering in the configuration for LDAP/active directory, I am able to do a successful test. But when I try to perform a sync, the app force logs me out. I alternatively try to use the CLI to try a sync and I get the following error message:
`PS C:\bwdc> .\bwdc.exe sync
Cannot read properties of null (reading 'directorySettings')`

I am not sure what I doing wrong or what I forgot to configure. Below is the directorySettings section of the data.json file that was created after using the directory connector app:
'    "directorySettings": {
      "directoryType": 0,
      "organizationId": "67482687-b08f-4263-ae0b-8dea427e0c69",
      "lastUserSync": null,
      "lastGroupSync": null,
      "lastSyncHash": null,
      "syncingDir": null,
      "sync": {
        "users": true,
        "groups": false,
        "interval": 5,
        "removeDisabled": true,
        "overwriteExisting": false,
        "largeImport": false,
        "useEmailPrefixSuffix": false,
        "creationDateAttribute": "whenCreated",
        "revisionDateAttribute": "whenChanged",
        "emailPrefixAttribute": "sAMAccountName",
        "memberAttribute": "member",
        "userObjectClass": "person",
        "groupObjectClass": "group",
        "userEmailAttribute": "mail",
        "groupNameAttribute": "name",
        "groupPath": "CN=Users",
        "userPath": "OU=Users,OU=IT,OU=Chatsworth"
      },
"userDelta": null,
"groupDelta": null
}, '

**Comment by Krychaz** [comment]
Hello there,

We use GitHub issues as a place to track bugs and other development related issues. Please write us using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
