### ISSUE TITLE
Azure BWDC -> Test feature shows "Deleted users" question

### ISSUE THREAD

**Issue by Ikallin** [bitwarden/directory-connector#49]
Hi,

So I tested the BWDC v2.6.2 with BW v1.34 and the sync works great. Except that in the "test" feature, it shows me all deleted users tag.
I know that it works and send the mail, but why do it shows tags ?
And, do it send the mail to deleted users ?

Thanks for your time !

Have a great day

**Comment by kspearrin** [comment]
Deleted users are not onboarded. They will not receive an email.
