### ISSUE TITLE
Multiple entries pulled with user@domain.com

### ISSUE THREAD

**Issue by steenstra** [bitwarden/directory-connector#493]
I get this error. Looks nice, but it is not really useful, since it doesn't tell me where to look to find the duplicate. 

```
Multiple entries pulled with john.smith@our.domain
```

Where did it pull them from? When I search AD for that user, I only get a single result. How can I troubleshoot this?

_Originally posted by @steenstra in https://github.com/bitwarden/directory-connector/issues/190#issuecomment-2178150165_

**Comment by steenstra** [comment]
Troubleshooting steps:
``` PowerShell
$env:BITWARDENCLI_CONNECTOR_DEBUG = "true"
bwdc test
```

The output is:
``` bwdc
Initializing lowdb storage service.
db file "C:\Users\myname\AppData\Roaming\Bitwarden Directory Connector\data.json already exists"; using existing db
acquiring db file lock
Attempting to create lowdb storage adapter.
Successfully created lowdb storage adapter.
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
acquiring db file lock
User search: OU=Users,OU=Resources,dc=bl,dc=local => (&(objectClass=person))
Deleted user search: CN=Deleted Objects,dc=bl,dc=local => (&(&(objectClass=person))(isDeleted=TRUE))
Group search: OU=Department Groups,OU=Groups,OU=Resources,dc=bl,dc=local => (&(objectClass=group))
Emails must be unique. Multiple entries pulled with the following emails:
john.smith@our.domain
```

There is only one john.smith in our organization, there are no other users who share the email address. Also, the user had never accepted their invite in bitwarden. I've removed the user there, but to no avail.
john.smith@our.domain

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by steenstra** [comment]
What exactly did you (try to) reproduce?

I think there are 2 problems:
1. The issue I'm having, which I agree could be a support issue
2. The fact that `bwdc` does not give useful information to troubleshoot the issue, which seems a problem that is easily reproducible and is, if not a bug, at least a lacking feature.

Anyway, the user still existed in the deleted users, from which they are now removed. Now `bwdc` returns an internal server error. Isn't that a bug?
