### ISSUE TITLE
GSuite group owners are not added to groups

### ISSUE THREAD

**Issue by infraweavers** [bitwarden/directory-connector#54]
When using this to sync from GSuite, if a user is an owner of the group they are not counted as being a member of the group; therefore they are not added to the group in Bitwarden.

Documentation for the API states that owners must be members of the group : 

> OWNER – This role can change send messages to the group, add or remove members, change member roles, change group's settings, and delete the group. An OWNER must be a member of the group. 

https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members

**Comment by infraweavers** [comment]
The same is true for the manager role

**Comment by kspearrin** [comment]
This should be fixed in our next update.

**Comment by infraweavers** [comment]
@kspearrin do you mean that the issue is already fixed in master (i.e. if we build the agent it'll work)? Do you know what the ETA will be for the next update/release?

**Comment by kspearrin** [comment]
@infraweavers It is fixed in master, yes. Not released yet. Hopefully soon.
