### ISSUE TITLE
Display the name of the currently logged in organisation 

### ISSUE THREAD

**Issue by autoantwort** [bitwarden/directory-connector#682]
I know I should not post feature requests here, but there is no category `directory-connector` in the feature request channel on https://community.bitwarden.com. 

If you are currently logged in, you have no idea for which organization you are logged in.

**Comment by BBGhub** [comment]
Hi There,

Thanks for the Feedback, this has been passed onto the team for review.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
