### ISSUE TITLE
An error has occured: Time Limit Exceeded

### ISSUE THREAD

**Issue by RogerSik** [bitwarden/directory-connector#69]
![07_08-51-39-MGMT bsc - Royal TS](https://user-images.githubusercontent.com/165814/95297265-6a74bd80-087a-11eb-86f8-8a8894605b99.png)

Which time limit? To bitwarden? (we are using vault.bitwarden.com) or the LDAP Server? Since migrating to vault.bitwarden.com from our selfhosted instance we are getting this messages multiple times.

**Comment by RogerSik** [comment]
Ok since we added 80 more users to the bitwarden LDAP group (now 180 users) we get this error. But why is there a timelimit? It works *sometimes* but mostly not.

**Comment by RogerSik** [comment]
With the option "Paged Search" we could prevent the OpenLDAP timelimit. It is possible that the error message can be more specific?

**Comment by kspearrin** [comment]
Unfortunately, we cannot control this error message since it comes from the LDAP querying library? Did you resolve the issue by using paged search?

**Comment by RogerSik** [comment]
I resolved it with the paged search. Would be nice to get information where the error happen (vault sync, ldap query). I thought first that the timeout was to vault.bitwarden.com
