### ISSUE TITLE
Sync AAD with userfilter produces error message

### ISSUE THREAD

**Issue by sammeidroid** [bitwarden/directory-connector#8]
When synchronizing an Azure AD when a user filter is set and a user without email is present in the AAD, the error message "Cannot read property 'trim' of undefined" appears and the synchronization or test sync aborts.

When a call comes from "azure-directory.services.ts" > "getUsers", the result string can be "undefined" (if the user does not have an email).

**Comment by kspearrin** [comment]
Thanks. Can you see if that fixed it? https://ci.appveyor.com/project/bitwarden/directory-connector/build/artifacts

**Comment by sammeidroid** [comment]
Thanks for the prompt reaction. I could now successfully synchronize AAD with filters.

**Comment by PsychoData** [comment]
I just ran into the same error, and the same thing is working for me
