### ISSUE TITLE
Azure Active Directory Sync Efficiency considerations

### ISSUE THREAD

**Issue by haneef95** [bitwarden/directory-connector#83]
Hi,

I've been checking through the request logs for the Azure Active Directory from Bitwarden Directory Connector...

### Current settings
![image](https://user-images.githubusercontent.com/298208/103577871-7568d980-4ecd-11eb-803c-e2751ad4ce3f.png)
Sync Users with `includeGroup` filter
Sync Groups with no filters

### Efficiency measures
1. BWDC downloads all the users through `https://graph.microsoft.com/v1.0/users?$select=id,mail,userPrincipalName,displayName,accountEnabled`, however, it doesn't need a list of all the users, as it does not manifest in to the Bitwarden Organisation (due to the `includeGroup` User Filter)

2. Because of the includeGroup filter, BWDC keeps doing numerous `https://graph.microsoft.com/v1.0/users/{id}/checkMemberGroups` requests.

I guess it would be sufficient to just make use of either of the following for each 'includeGroup':
- `https://graph.microsoft.com/v1.0/groups/{groupId}/members?$select=id,mail,userPrincipalName,displayName,accountEnabled` - for direct members
- or `https://graph.microsoft.com/v1.0/groups/{groupId}/transitiveMembers?$select=id,mail,userPrincipalName,displayName,accountEnabled` - for nested members

3. BWDC downloads the members of every group, which does not manifest onto the Bitwarden Organisation, so, I believe that wouldn't be necessary either?

**Comment by checkso** [comment]
This definitley needs to be addressed. 
In our tenant it takes ages to get all users.

**Comment by haneef95** [comment]
I'm just thinking, it'll be a lot better if SCIM was implemented as part of the Bitwarden Public API. It has major benefits. AzureAD supports automatic provisioning through SCIM.

This has little votes, hopefully, it picks up: https://community.bitwarden.com/t/scim-as-an-alternative-to-directory-connector-for-user-management/28913

**Comment by differsthecat** [comment]
Fixed 👍

**Comment by haneef95** [comment]
Happy to see this in the release:

> Directory Connector - Azure AD Sync Performance: Performance for Directory Connector syncs against Azure Active Directory has been improved. Organizations syncing with Azure AD will not need to change their sync configuration.
https://bitwarden.com/help/releasenotes/#2022-02-08
